### ISSUE TITLE
[feature request] Implement Stebalien's `Owidth` formatting command for paddings?

### ISSUE THREAD

**Issue by ghost** [krypt-n/bar#21]
Hi,

is there any chance that you could implement [Stebalien's `Owidth` formatting command](https://github.com/Stebalien/bar/commit/892e43a3bc25b78af44b366996532da7f44abc20) for paddings?

I think that's a pretty elegant possibility to position blocks more freely than lemonbar allows you to ootb (and I quite don't like using [workarounds like using spaces etc.](https://github.com/LemonBoy/bar/issues/168#issuecomment-185308702)).

**Comment by krypt-n** [comment]
Since you seem to have a specific usecase for this, could you take a look at the [offset-test](https://github.com/krypt-n/bar/tree/offset-test) branch and tell me if Stebalien's patch behaves as expected?
The interaction with alignment seems to be a bit confusing to me.
I will merge the patch into xft-port if it doesn't break anything.

**Comment by ghost** [comment]
First of all, thank you very much for your efforts!

I've been testing lemonbar from your offset-test branch now for a while, and I didn't encounter any issues so long; for me, Stebalien's patch works as expected.

**Comment by krypt-n** [comment]
Okay, thanks for your help.

**Comment by ghost** [comment]
Thanks for accepting this request!
