### ISSUE TITLE
Faraway unicode symbols (☢,⚙, …)  not displayed.

### ISSUE THREAD

**Issue by jpotier** [krypt-n/bar#22]
When I enter this:
`echo "☢☢☢" | lemonbar -f "hack:size=8" -p`
It shows nothing. My font (hack) has the glyph.

Is it something related to multibyte utf8?

I opened a new issue on your fork as I suspect it is associated with XFT. If, not, I'll report it in the original repo too.

**Comment by krypt-n** [comment]
Are you sure that hack contains a glyph for ☢ or ⚙?
XftCharExists returns false for the UTF16 character `0x2622` (☢) and hack from ttf-hack, installed from Arch repos.

If you, for example, run lemonbar-xft with DejaVu Sans it displays ☢ and ⚙ correctly (since they are three byte sequences in UTF8).

**Comment by jpotier** [comment]
Oh! So it would mean that when I enter these character in my terminal, they are replaced on-the-fly from a backup font? Possible, I actually hadn't checked.

My bad…

Would it be be hard to have this fallback mechanism for missing unicode characters in the font that is used?

**Comment by krypt-n** [comment]
Fallback fonts are one of the reasons this fork exists. Using multiple fonts does just that:

```
echo "test☢" | lemonbar  -f "hack" -f "dejavu sans" -p
```

**Comment by jpotier** [comment]
Oh cool!! I didn't know!!
